
# For each fengine, specify the host ip address (host_ip), destination port (dest_port),
# the antenna numbers it is processing (ants).
#
# The following booleans can also be set-
# if it needs to be initialized (init),
# if you want to set noise (noise),
# or test vector (tvg) input and if you want it to
# send data over ethernet (eth).
#
# If a specific boolean task needs to be implemented on all fengines, you can
# set it as a global parameter.
#
# NB: If fengine antennas are not specified, they will be alloted according the order in
# which they are presented here.

# You can set the following global parameters for all fengines
# or enable them for only some fengines. The global parameters
# overrride the individual fengine settings.

# You can sync the fengines using an external PPS signal
# or manually using a software register.
# Choices: 'pps', 'manual', False (default: 'pps')
sync: 'pps'

# The test vector generator can operate in multiple modes:
# 'const_ants' : Writes a different constant value
#                to all channels of an antenna (both pols).
# 'const_pols' : Write a different constant value
#                to both pols of an antenna.
# 'ramp'       : Write the same ramp to all pols.
# 'ramp_pols'  : Write a different ramp to each pol.
# False        : Do not set the test vector (default)
tvg: False

# Turn on the noise generator for testing
noise: False

initialize: False

# Disable transmission for all fengines
eth: False

# FFT shift. One bit per FFT stage, the first stage is the LSB
# If the FFT uses bit growth, some or all of the stages may be ignored
fft_shift: 0x1557 

# Specify a full path to an F-Engine fpg files
# or redis:<fpg filename> if the fpg file has been uploaded to redis
#fpgfile: '/home/hera/src/hera_corr_f/snap_fengine/outputs/snap_fengine.fpg'
fpgfile: '/home/hera/src/hera_corr_f/snap_fengine/outputs/snap_fengine_2021-03-03_1621.fpg'

# Destination port for SNAP data
dest_port: 8511

# Phase switch step period
# 2**18 * 2**log_walsh_step_size is the period in 250MHz FPGA clocks of the shortest walsh step
log_walsh_step_size: 3
# Order of walsh matrix (i.e., number of independent patterns possible)
walsh_order: 32
# Delay between modulation and demodulation, in units of 250MHz FPGA clock cycles.
# Used to compensate for cable delays
walsh_delay: 600

fengines:
    heraNode12Snap0:
        phase_switch_index: [1,2,3,4,5,6]
        ants: [84, 85, 86]
    heraNode12Snap1:
        phase_switch_index: [7,8,9,10,11,12]
        ants: [87, 88, 89]
    heraNode12Snap2:
        phase_switch_index: [13,14,15,16,17,18]
        ants: [90, 91, 92]
    heraNode12Snap3:
        phase_switch_index: [19,20,21,22,23,24]
        ants: [93, 94, 95]
    heraNode0Snap0:
        phase_switch_index: [1,2,3,4,5,6]
        ants: [0, 1, 2]
    heraNode0Snap1:
        phase_switch_index: [7,8,9,10,11,12]
        ants: [3, 4, 5]
    heraNode0Snap2:
        phase_switch_index: [13,14,15,16,17,18]
        ants: [6, 7, 8]
    heraNode0Snap3:
        phase_switch_index: [19,20,21,22,23,24]
        ants: [9, 10, 11]
    heraNode8Snap0:
        phase_switch_index: [1,2,3,4,5,6]
        ants: [12, 13, 14]
    heraNode8Snap1:
        phase_switch_index: [7,8,9,10,11,12]
        ants: [15, 16, 17]
    heraNode8Snap2:
        phase_switch_index: [13,14,15,16,17,18]
        ants: [18, 19, 20]
    heraNode8Snap3:
        phase_switch_index: [19,20,21,22,23,24]
        ants: [21, 22, 23]
## MJK: 21 AUG 2020 Node 9 completely unreachable wr-reports DOWN
## ARP 08/21/20 WR on Node9 not communicating, no phase lock, needs reboot
## ARP 09/03/20 reboot successful; WR fixed
## ARP 10/07/20 node power was left off, removing Node9 for next obs session
    heraNode9Snap0:
        phase_switch_index: [1,2,3,4,5,6]
        ants: [24, 25, 26]
    heraNode9Snap1:
        phase_switch_index: [7,8,9,10,11,12]
        ants: [27, 28, 29]
    heraNode9Snap2: # ARP 2/28/20 unpingable 3/3/20 restored
        phase_switch_index: [13,14,15,16,17,18]
        ants: [30, 31, 32]
    heraNode9Snap3: # ARP 2/28/20 failed to sync 9/3/20 TFTP errors
        phase_switch_index: [19,20,21,22,23,24]
        ants: [33, 34, 35]
    heraNode7Snap0:
        phase_switch_index: [1,2,3,4,5,6]
        ants: [36, 37, 38]
    heraNode7Snap1:
        phase_switch_index: [7,8,9,10,11,12]
        ants: [39, 40, 41]
    heraNode7Snap2:
        phase_switch_index: [13,14,15,16,17,18]
        ants: [42, 43, 44]
#  JK:  MMCM not locking. 
#    heraNode7Snap3:
#        phase_switch_index: [19,20,21,22,23,24]
#        ants: [45, 46, 47]
## WR in Node4 deactivated due to packet issues
##    heraNode4Snap0: # ARP: not syncing 2/28/20
##        phase_switch_index: [1,2,3,4,5,6]
##        ants: [48, 49, 50]
##    heraNode4Snap1:
##        phase_switch_index: [7,8,9,10,11,12]
##        ants: [51, 52, 53]
##    heraNode4Snap2:
##        phase_switch_index: [13,14,15,16,17,18]
##        ants: [54, 55, 56]
##    heraNode4Snap3:
##        phase_switch_index: [19,20,21,22,23,24]
##        ants: [57, 58, 59]
    heraNode5Snap0: # ARP 2/28/20 not syncing
        phase_switch_index: [1,2,3,4,5,6]
        ants: [60, 61, 62]
#  JK: MMCM not locking: Still broken (20-Jan-21)
#    heraNode5Snap1:
#        phase_switch_index: [7,8,9,10,11,12]
#        ants: [63, 64, 65]
# ARP commented this out 2/18/20 b/c ADC failed to configure 5 times
# MJK  20 AUG 2020 initialization still failing 5 times, auto-removed regularly so leaving out
#    heraNode5Snap2:
#        phase_switch_index: [13,14,15,16,17,18]
#        ants: [66, 67, 68]
#
#  JK: Node5Snap3 is being flaky (lots of working then not working and reint required) 22-Jan-21
#    heraNode5Snap3:
#        phase_switch_index: [19,20,21,22,23,24]
#        ants: [69, 70, 71]
#  JK: node13 not turning on (20-Jan-21)
#    heraNode13Snap0:
#        phase_switch_index: [1,2,3,4,5,6]
#        ants: [72, 73, 74]
#    heraNode13Snap1:
#        phase_switch_index: [7,8,9,10,11,12]
#        ants: [75, 76, 77]
#    heraNode13Snap2:
#        phase_switch_index: [13,14,15,16,17,18]
#        ants: [78, 79, 80]
#    heraNode13Snap3:
#        phase_switch_index: [19,20,21,22,23,24]
#        ants: [81, 82, 83]
## ARP 08/21/20 WR on Node3 not communicating, no phase lock
## ARP 08/26/20 power cycle fixed
## ARP 10/07/20 WR "active" but not in PHASE_LOCK, some evidence that it may drift out of lock, deactivating for now
#    heraNode3Snap0:
#        phase_switch_index: [1,2,3,4,5,6]
#        ants: [96, 97, 98]
#    heraNode3Snap1:
#        phase_switch_index: [7,8,9,10,11,12]
#        ants: [99, 100, 101]
#    heraNode3Snap2:
#        phase_switch_index: [13,14,15,16,17,18]
#        ants: [102, 103, 104]
#    heraNode3Snap3:
#        phase_switch_index: [19,20,21,22,23,24]
#        ants: [105, 106, 107]
    heraNode10Snap0:
        phase_switch_index: [1,2,3,4,5,6]
        ants: [108, 109, 110]
    heraNode10Snap1:
        phase_switch_index: [7,8,9,10,11,12]
        ants: [111, 112, 113]
    heraNode10Snap2:
        phase_switch_index: [13,14,15,16,17,18]
        ants: [114, 115, 116]
    heraNode10Snap3:
        phase_switch_index: [19,20,21,22,23,24]
        ants: [117, 118, 119]
    heraNode14Snap0:
        phase_switch_index: [1,2,3,4,5,6]
        ants: [120, 121, 122]
    heraNode14Snap1:
        phase_switch_index: [7,8,9,10,11,12]
        ants: [123, 124, 125]
    heraNode14Snap2:
        phase_switch_index: [13,14,15,16,17,18]
        ants: [126, 127, 128]
    heraNode14Snap3:
        phase_switch_index: [19,20,21,22,23,24]
        ants: [129, 130, 131]
    heraNode1Snap0:
        phase_switch_index: [1,2,3,4,5,6]
        ants: [132, 133, 134]
    heraNode1Snap1:
        phase_switch_index: [7,8,9,10,11,12]
        ants: [135, 136, 137]
    heraNode1Snap2:
        phase_switch_index: [13,14,15,16,17,18]
        ants: [138, 139, 140]
    heraNode1Snap3:
        phase_switch_index: [19,20,21,22,23,24]
        ants: [141, 142, 143]
# JK: MMCM not locking 22-Jan-21
#    heraNode15Snap0:
#        phase_switch_index: [1,2,3,4,5,6]
#        ants: [144, 145, 146]
#    heraNode15Snap1:
#        phase_switch_index: [7,8,9,10,11,12]
#        ants: [147, 148, 149]
#    heraNode15Snap2:
#        phase_switch_index: [13,14,15,16,17,18]
#        ants: [150, 151, 152]
#    heraNode15Snap3:
#        phase_switch_index: [19,20,21,22,23,24]
#        ants: [153, 154, 155]
#
# Data is sent assuming a total of 32 Xengines and
# a maximum of 48 channels per Xengine. If all the
# 32 Xengines are not defined, the corresponding channels
# are not sent anywhere.
xengines:
    0:
        even:
           ip: "10.80.40.197"
           mac: 0x02020a5028c5
        odd:
           ip: "10.80.40.206"
           mac: 0x02020a5028ce
        chan_range: [1536, 1920]
    1:
        even:
           ip: "10.80.40.229"
           mac: 0x02020a5028e5
        odd:
           ip: "10.80.40.238"
           mac: 0x02020a5028ee
        chan_range: [1920, 2304]
    2:
        even:
           ip: "10.80.40.198"
           mac: 0x02020a5028c6
        odd:
           ip: "10.80.40.207"
           mac: 0x02020a5028cf
        chan_range: [2304, 2688]
    3:
        even:
           ip: "10.80.40.230"
           mac: 0x02020a5028e6
        odd:
           ip: "10.80.40.239"
           mac: 0x02020a5028ef
        chan_range: [2688, 3072]
    4:
        even:
           ip: "10.80.40.199"
           mac: 0x02020a5028c7
        odd:
           ip: "10.80.40.208"
           mac: 0x02020a5028d0
        chan_range: [3072, 3456]
    5:
        even:
           ip: "10.80.40.231"
           mac: 0x02020a5028e7
        odd:
           ip: "10.80.40.240"
           mac: 0x02020a5028f0
        chan_range: [3456, 3840]
    6:
        even:
           ip: "10.80.40.200"
           mac: 0x02020a5028c8
        odd:
           ip: "10.80.40.209"
           mac: 0x02020a5028d1
        chan_range: [3840, 4224]
    7:
        even:
           ip: "10.80.40.232"
           mac: 0x02020a5028e8
        odd:
           ip: "10.80.40.241"
           mac: 0x02020a5028f1
        chan_range: [4224, 4608]
    8:
        even:
           ip: "10.80.40.201"
           mac: 0x02020a5028c9
        odd:
           ip: "10.80.40.210"
           mac: 0x02020a5028d2
        chan_range: [4608, 4992]
    9:
        even:
           ip: "10.80.40.233"
           mac: 0x02020a5028e9
        odd:
           ip: "10.80.40.242"
           mac: 0x02020a5028f2
        chan_range: [4992, 5376]
    10:
        even:
           ip: "10.80.40.202"
           mac: 0x02020a5028ca
        odd:
           ip: "10.80.40.211"
           mac: 0x02020a5028d3
        chan_range: [5376, 5760]
    11:
        even:
           ip: "10.80.40.234"
           mac: 0x02020a5028ea
        odd:
           ip: "10.80.40.243"
           mac: 0x02020a5028f3
        chan_range: [5760, 6144]
    12:
        even:
           ip: "10.80.40.203"
           mac: 0x02020a5028cb
        odd:
           ip: "10.80.40.212"
           mac: 0x02020a5028d4
        chan_range: [6144, 6528]
    13:
        even:
           ip: "10.80.40.235"
           mac: 0x02020a5028eb
        odd:
           ip: "10.80.40.244"
           mac: 0x02020a5028f4
        chan_range: [6528, 6912]
    14:
        even:
           ip: "10.80.40.204"
           mac: 0x02020a5028cc
        odd:
           ip: "10.80.40.213"
           mac: 0x02020a5028d5
        chan_range: [6912, 7296]
    15:
        even:
           ip: "10.80.40.236"
           mac: 0x02020a5028ec
        odd:
           ip: "10.80.40.245"
           mac: 0x02020a5028f5
        chan_range: [7296, 7680]
