# The fpgfile that the SNAP boards have to be programmed with. 
# Set the 'p' flag with calling the init script to program the boards.
fpgfile: '/home/deepthi/herafengine/snap_fengine/outputs/snap_fengine_2018-06-07_0929.fpg'

fengines:
    snapc57:
        host_ip: '10.10.10.157'
        dest_port: 8511
        ant_range: [48,60]
#    snap109:
#        host_ip: '10.10.10.109'
#        dest_port: 8511
#        ant_range: [0,12]
#    snap111:
#        host_ip: '10.10.10.111'
#        dest_port: 8511
#        ant_range: [0,12]
#    snap1:
#        host_ip: '10.10.10.201'
#        dest_port: 8511
#        ant_range: [48,60]

# Data can be alloted to (48/num_ants_per_feng) 
# number of X-engines. 384 channels are sent to 
# each Xeng specified.

xengines:
    xeng0:
        num: 0
        even:
           ip: "10.10.10.136"
           mac: 0x02020a140102
        odd:
           ip: '0.0.0.0' #nowhere
           mac: 0x000000000000
        chan_range: [0,384]
    xeng1:
        num: 1
        even:
           ip: "10.10.10.136"
           mac: 0x02020a140102
        odd:
           ip: '0.0.0.0'
           mac: 0x000000000000
        chan_range: [384,768]
