#
# For each fengine, specify the host ip address (host_ip), destination port (dest_port),
# the antenna numbers it is processing (ants). 
#
# The following booleans can also be set- 
# if it needs to be initialized (init), 
# if you want to set noise (noise), 
# or test vector (tvg) input and if you want it to 
# send data over ethernet (eth).
#
# If a specific boolean task needs to be implemented on all fengines, you can 
# set it as a global parameter.
#
# NB: If fengine antennas are not specified, they will be alloted according the order in 
# which they are presented here.

# You can set the following global parameters for all fengines 
# or enable them for only some fengines. The global parameters 
# overrride the individual fengine settings.

# You can sync the fengines using an external PPS signal
# or manually using a software register. 
# Choices: 'pps', 'manual', False (default: 'pps')
sync: 'pps'

# The test vector generator can operate in multiple modes:
# 'const_ants' : Writes a different constant value 
#                to all channels of an antenna (both pols).
# 'const_pols' : Write a different constant value  
#                to both pols of an antenna.
# 'ramp'       : Write the same ramp to all pols.
# 'ramp_pols'  : Write a different ramp to each pol.
# False        : Do not set the test vector (default) 
tvg: False

# Turn on the noise generator for testing
noise: False

initialize: False

# Disable transmission for all fengines
eth: False

# Specify a full path to an F-Engine fpg files
fpgfile: '/home/hera/src/hera_corr_f/snap_fengine/outputs/snap_fengine_2018-07-10_1618.fpg'

# Destination port for SNAP data
dest_port: 8511

fengines:
    heraNode1Snap0:
        phase_switch_index: 0
    heraNode1Snap1:
        phase_switch_index: 0
    heraNode1Snap2:
        phase_switch_index: 0

# Data is sent assuming a total of 32 Xengines and 
# a maximum of 48 channels per Xengine. If all the 
# 32 Xengines are not defined, the corresponding channels
# are not sent anywhere.
xengines:
    xeng0:
        even:
           ip: "10.80.40.223"
           mac: 0x02020a5028c5
        odd:
           ip: '0.0.0.0' #nowhere
           mac: 0x000000000000
    xeng1:
        even:
           ip: "10.80.40.224"
           mac: 0x02020a5028c6
        odd:
           ip: '0.0.0.0' #nowhere
           mac: 0x000000000000
